/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rfid_project;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import rfid_project.DatabaseUltils.OrderDetailDAO;
import rfid_project.DatabaseUltils.ProductDAO;
import rfid_project.Entity.OrderDetail;

/**
 *
 * @author LENOVO
 */
public class DetailPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailPanel
     */
    OrderDetailDAO detaildao = new OrderDetailDAO();
    ProductDAO productdao = new ProductDAO();
    public DetailPanel(String orderid) {
        initComponents();
        loadData(orderid);
        
    }
    public void loadData(String orderid){
        DefaultTableModel model  = (DefaultTableModel)jTable1.getModel();
        List<OrderDetail> details = detaildao.getOrderDetail2(orderid);
        model.setRowCount(0);
        Object[] ob = new Object[4];
        for(int i = 0;i<details.size();i++){
            ob[0] = details.get(i).getOrderID();
            ob[1] = productdao.getProductById(details.get(i).getProductID()).getName();
            ob[2] = details.get(i).getQuantity();
            ob[3] = details.get(i).getTotalItem();
            model.addRow(ob);
         }
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Product", "Quantity", "Total Item"
            }
        ));
        jTable1.setFillsViewportHeight(true);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
