/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package rfid_project;

import java.awt.Dimension;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Timer;
import java.util.TimerTask;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import rfid_project.DatabaseUltils.OrderDAO;
import rfid_project.DatabaseUltils.OrderDetailDAO;
import rfid_project.Entity.Order;
import rfid_project.Entity.Tag2;

/**
 *
 * @author LENOVO
 */
public class OrderHandler extends javax.swing.JPanel {

    /**
     * Creates new form OrderHandler
     */
    DefaultTableModel model;
    List<Order> orders;
    public OrderDAO orderdao = new OrderDAO();
    public OrderDetailDAO detaildao = new OrderDetailDAO();
    public OrderHandler() {
        initComponents();
         model = (DefaultTableModel)jTable1.getModel();
         orders = orderdao.getOrderToPull();
        model.setRowCount(0);
        Object[] obj = new Object[4];
        for(Order o : orders){
            obj[0] = o.getOrderID();
            obj[1] = o.getOrderdate();
            obj[2] = (int)o.getTotal();
            if(o.getStatus()== 1){
                obj[3] = "Pending";
            }else{
                if(o.getStatus()==2){
                     obj[3] = "Progress";
                }
                if(o.getStatus()==3){
                     obj[3] = "finish";
                }
            }
            
             model.addRow((obj));
        }
        model.fireTableDataChanged();
        // create JTable with default data
       
    }
    public  void updateTable(){
        model = (DefaultTableModel)jTable1.getModel();
        List<Order> orders = orderdao.getOrderToPull();
        model.setRowCount(0);
        Object[] obj = new Object[4];
        for(Order o : orders){
            obj[0] = o.getOrderID();
            obj[1] = o.getOrderdate();
            obj[2] = (int)o.getTotal();
            if(o.getStatus()== 1){
                obj[3] = "Pending";
            }else{
                if(o.getStatus()==2){
                     obj[3] = "Progress";
                }
                if(o.getStatus()==3){
                     obj[3] = "finish";
                }
            }
            
             model.addRow((obj));
        }
        model.fireTableDataChanged();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Date", "Total", "Status"
            }
        ));
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setFillsViewportHeight(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Tạo mới");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("Xuất đơn");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Xuất đơn");

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rfid_project/images/Refresh-icon (1).png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton3.setText("Single");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton5.setText("Auto");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton6.setText("Stop");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Danh sách sản phẩm");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(49, 49, 49)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       JFrame f = new JFrame();
        CreateOrder orr = new CreateOrder();
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(650,450));
        panel.add(orr);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.add(panel);
        f.setSize(650, 550);
        f.setLocationByPlatform(true);
        f.pack();
        f.setVisible(true);
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        updateTable();
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        System.out.println(model.getValueAt(jTable1.getSelectedRow(), 0));
        Order o = new Order();
        String statusvalue = (String)model.getValueAt(jTable1.getSelectedRow(), 3);
        int value =0;
        if(statusvalue.equals("Pending")){
            value=1;
        }else{
            if(statusvalue.equals("Progress")){
                value=2;
            }
        }
        if(((value == 2)) || ((value == 3))){
            JOptionPane.showMessageDialog(this, "Ðơn hàng đang được xuất");
        }
        else{
            o.setOrderID((String)model.getValueAt(jTable1.getSelectedRow(), 0));
            o.setTotal((int)model.getValueAt(jTable1.getSelectedRow(), 2));
            o.setStatus(value+1);
            orderdao.updateOrder(o);
            updateTable();
        }
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	//testdemo.demos.add(new Tag2("00FF F145 2000 4093 CE01 00F9"));//pd1
    	//testdemo.demos.add(new Tag2("300F 4F57 3AD0 01C0 8369 A245"));//pd1
    //	testdemo.demos.add(new Tag2("300F 4F57 3AD0 01C0 8369 A249"));
    	//testdemo.demos.add(new Tag2("300F 4F57 3AD0 01C0 8369 A258"));
        try{
            DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
    	TagReportListenerImplementation2.orderScan = orderdao.getOrderBy((String)model.getValueAt(jTable1.getSelectedRow(), 0)).get(0);  	
    	TagReportListenerImplementation2.orderScan.setOrderdetails(detaildao.getOrderDetail2((String)model.getValueAt(jTable1.getSelectedRow(), 0)));
    	TagReportListenerImplementation2.flag1 = 1;
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Vui lòng chon don hang");
        }
    	
        
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	TagReportListenerImplementation2.flag1 = 1;
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    	TagReportListenerImplementation2.flag1 = 0;
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JFrame f = new JFrame();
        ProductPanel panelP = new ProductPanel();
        panelP.loadData();
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(500,400));
        panel.add(panelP);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.add(panel);
        f.setSize(650, 550);
        f.setLocationByPlatform(true);
        f.pack();
        f.setVisible(true);
// TODO add your handling code here:
    }                                        

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        int row = jTable1.getSelectedRow();
        String pid  = (String)jTable1.getValueAt(row, 0);
        if(pid.equals("")){
            JOptionPane.showMessageDialog(this, "Phòng rỗng");
        }else{
            JFrame f = new JFrame();
        DetailPanel panelP = new DetailPanel(pid);
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(400,300));
        panel.add(panelP);
        f.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        f.add(panel);
        f.setSize(650, 550);
        f.setLocationByPlatform(true);
        f.pack();
        f.setVisible(true);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
